### ISSUE TITLE
라이선스 문의

### ISSUE THREAD

**Issue by L4by** [logs3/cleaner#3]
레포지토리에 작성한 코드에 대한 이용허락 조건이 기재되어 있지 않은데 해당 코드를 수정 후 재배포하려면 어떤 라이선스를 따라야 하나요?

**Comment by logs3** [comment]
수익창출하지않는한 마음대로 사용가능합니다~

물론 재배포도요 ><

2019년 11월 3일 (일) 10:30, Laby <notifications@github.com>님이 작성:

**Comment by L4by** [comment]
확인했습니다. 감사합니다!
